<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.6</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>org.example</groupId>
    <artifactId>Esports-manager</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>26</maven.compiler.source>
        <maven.compiler.target>26</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <packaging>pom</packaging>
    <modules>
        <module>Msvcs-inscripciones</module>
        <module>Msvcs-equipos</module>
        <module>Msvcs-juegos</module>
        <module>Msvcs-notificaciones</module>
        <module>Msvcs-partidas</module>
        <module>Msvcs-premios</module>
        <module>Msvcs-rankings</module>
        <module>Msvcs-resultados</module>
        <module>Msvcs-sanciones</module>
        <module>Msvcs-torneos</module>
        <module>Msvcs-usuarios</module>
        <module>Msvcs-eureka</module>
        <module>Msvcs-gateway</module>
    </modules>

</project>